docs: added api key setup to readme
follow-the-nft/follow-the-nft-api pull request #29
Opened 2021-12-08 05:05 UTC by vbchomp

2021-12-08 05:46 UTC, fadnesscharlie approved these changes
I approve of this message

2021-12-09 07:11 UTC, MuckT requested changes

2021-12-09 07:11 UTC, MuckT commented on README.md
> +fetch('https://api.opensea.io/api/v1/asset/0xb47e3cd837ddf8e4c57f05d70ab865de6e193bbb/1/', options)
Lets include an example using `axios` as opposed to fetch.

2021-12-10 03:52 UTC, closed without merging

2021-12-10 03:53 UTC, vbchomp commented
cannot get the file to change in pr.