auth files
follow-the-nft/follow-the-nft-api pull request #35
Opened 2021-12-09 05:26 UTC by jeremywbrazell

Created auth files for basic and bearer authentication.  Pushing up for review.

2021-12-09 07:04 UTC, MuckT requested changes

2021-12-09 07:04 UTC, MuckT commented on package.json
> +    "superagent": "^6.1.0"
Think a few of these can move to dev dependencies like `nodemon`. I'd also suggest we remove `morgan` and use a different logger if possible. Let's also see if we can get `axios` working without method override.

2021-12-09 07:04 UTC, MuckT commented on src/error-handlers/acl.js
> +'use strict'
This file looks like a duplicate of the one in middleware. Lets delete it.

2021-12-09 07:04 UTC, MuckT commented on src/middleware/basic.js
> +  function _authError() {
lets rename this function to remove the `_` as this doesn't appear to be recursive. If it's use commonly we can keep it, but haven't seen this before.

2021-12-09 07:04 UTC, MuckT commented on src/middleware/bearer.js
> +  function _authError() {
Same comment as with basic around `_authError()`.

2021-12-09 07:04 UTC, MuckT commented on src/models/modelsIndex.js
> +const investorModel = require('./investor.js')
Remove investor model.

2021-12-10 02:42 UTC, MuckT approved these changes
LGMT!

2021-12-10 02:42 UTC, fadnesscharlie approved these changes
I approve

2021-12-10 02:46 UTC, merged